/**
 * Classify
 * Classify Custom Image Recognition Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@inoven.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.io.File;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineObject1 {
  
  @SerializedName("model_id")
  private String modelId = null;
  @SerializedName("tag")
  private String tag = null;
  @SerializedName("file")
  private File file = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getModelId() {
    return modelId;
  }
  public void setModelId(String modelId) {
    this.modelId = modelId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }
  public void setTag(String tag) {
    this.tag = tag;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public File getFile() {
    return file;
  }
  public void setFile(File file) {
    this.file = file;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject1 inlineObject1 = (InlineObject1) o;
    return (this.modelId == null ? inlineObject1.modelId == null : this.modelId.equals(inlineObject1.modelId)) &&
        (this.tag == null ? inlineObject1.tag == null : this.tag.equals(inlineObject1.tag)) &&
        (this.file == null ? inlineObject1.file == null : this.file.equals(inlineObject1.file));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.modelId == null ? 0: this.modelId.hashCode());
    result = 31 * result + (this.tag == null ? 0: this.tag.hashCode());
    result = 31 * result + (this.file == null ? 0: this.file.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject1 {\n");
    
    sb.append("  modelId: ").append(modelId).append("\n");
    sb.append("  tag: ").append(tag).append("\n");
    sb.append("  file: ").append(file).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
